openapi: "3.0.0"
info:
  version: 1.0.0
  title: Joke Website
x-yc-apigateway:
  service_account_id: { JOKE_SERVICE_ACCOUNT_ID }

paths:
  /:
    get:
      operationId: index
      x-yc-apigateway-integration:
        type: object_storage
        bucket: { JOKE_WEBSITE_BUCKET }
        object: 'index.html'